openapi: 3.0.3
info:
  title: WasaPhoto API
  description: |
    Questa API permette agli utenti 
    l'utilizzo di tutti i servizi offerti dal sito
    WasaPhoto.
  version: 1.0.0

tags: 
  - name: "login"
    description: Gestione del login
  - name: "user"
    description: Gestione servizi utente
  - name: "banned"
    description: Gestione ban dell'utente
  - name: "following"
    description: Gestione following dell'utente
  - name: "images"
    description: Gestione immagini dell'utente
  - name: "comment"
    description: Gestione dei commenti delle immagini dell'utente
  - name: "like"
    description: Gestione dei like delle immagini dell'utente

components: 
    schemas:
      #
      user:
        title: User structure
        description: "Questo oggetto rappresenta un singolo utente"
        type: object
        properties:      
          name:
            description: Username dell'utente
            type: string
            pattern: '^.*?$'
            example: LikeMrSarri
            minLength: 3
            maxLength: 16
          userId:
            description: Identificatore univoco dell'utente
            type: integer
            example: 71
          follower:
            description: Array di identificatori di utenti che seguono questo utente
            type: array
            minItems: 0
            maxItems: 9999
            items: 
              type: integer
          following:
            description: Array di identificatori di utenti che questo utente segue
            type: array
            minItems: 0
            maxItems: 9999
            items: 
              type: integer
          banList:
            description: Array di identificatori di utenti che questo utente ha bloccato
            type: array
            minItems: 0
            maxItems: 9999
            items: 
              type: integer
      #
      image:
        title: Image structure
        description: "Questo oggetto rappresenta una singola immagine"
        type: object
        properties:
          imgId: 
            description: Identificatore univoco dell'immagine
            type: string
            pattern: '^.*?$'
            minLength: 4
            maxLength: 25
            example: Lu71cf2g23
          file:
            description: Il file che rappresenta l'immagine
            type: string
            minLength: 0
            maxLength: 10000
            format: binary
          descrizione: 
            description: Descrizione scritta dall'utente che ha postato l'immagine
            type: string
            pattern: '^.*?$'
            minLength: 0
            maxLength: 280
            example: foto al mare! hashtag io volevo andare in montagna
          like:
            description: Array di identificatori di utenti che hanno messo like alla foto
            type: array
            minItems: 0
            maxItems: 9999
            items: 
              type: integer
          comments:
            description: Array di identificatori di utenti che hanno commentato la foto e il loro commento
            type: array
            minItems: 0
            maxItems: 9999
            items:
              type: object
              properties:
                idComment:
                  type: string
                  description: id del commento
                  pattern: '^.*?$'
                  minLength: 4
                  maxLength: 25
                  example: agfhd029f2f
                text:
                  type: string
                  description: testo del commento
                  pattern: '^.*?$'
                  minLength: 1
                  maxLength: 80
                  example: bella foto!
                commenter:
                  description: utente che ha commentato
                  type: integer
          author:
            description: Identificatore utente che ha postato la foto
            type: integer
            example: 71
      #      
    securitySchemes:
      bearerAuth:
        type: http
        scheme: bearer      

paths:
  #
  /user/{idUser}:

    parameters: 
    - name: idUser
      in: path
      required: true
      description: id dell'utente della pagina visitata
      schema:
        type: integer
        description: es /user/260513

    put: 
      summary: Modifica nome utente
      description: l'operazione consente la modifica del nome utente 
      tags: ["user"]
      operationId: setMyUserName
      requestBody:
        content: 
          application/json: 
            schema: 
              type: string
              pattern: '^.*?$'
              example: LikeMrSarri2
              minLength: 3
              maxLength: 16
              
      responses: 
        "201":
          description: Successo, user name modificato.
          content: 
            application/json: 
              schema: 
                $ref: "#/components/schemas/user"
        "404":
          description: Errore, utente non trovato!

      security:
        - bearerAuth: []

    get:
      summary: Ritorna il profilo utente
      description: l'operazione ritorna tutte le informazioni del profilo dell'utente 
      tags: ["user"]
      operationId: getUserProfile
      responses: 
        "200":
          description: Successo, ricevuto l' object che rappresenta l'utente.
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/user"
        "404":
          description: Errore, utente non trovato!

      security:
        - bearerAuth: []


  #  
  /user/{idUser}/following/:  #con o senza / finale

    parameters: 
    - name: idUser
      in: path
      required: true
      description: id dell'utente della pagina visitata
      schema:
        type: integer
        description: es /user/260513/following/

    get:
      summary: stream following utente
      description: l'operazione ritorna in un array tutti i followed dell'utente, in modo tale da creare il suo stream
      tags: ["following"]
      operationId: getMyStream
      responses:
        "200":
          description: Successo, ricevuto tutti i following dell'utente.
          content:
            application/json:
              schema:
                type: array
                minItems: 0
                maxItems: 999
                items:
                  $ref: "#/components/schemas/user"
      
      security:
        - bearerAuth: []

  #
  /user/{idUser}/following/{followedUserId}: 

    parameters: 
    - name: idUser
      in: path
      required: true
      description: id dell'utente della pagina visitata
      schema:
        type: integer
        description: es /user/260513/following/xxx


    - name: followedUserId
      in: path
      required: true
      description: id dell'utente seguito
      schema:
        type: integer
        description: es /user/260513/following/150519


    delete:
      summary: unfollow di un utente
      description: l'operazione elimina il followedUserId dall'array di seguiti dell'utente
      tags: ["following"]
      operationId: unfollowUser
      responses:
        "204":
          description: "Successo, utente non più seguito"
        "404":
          description: Errore, utente non trovato!
      security:
        - bearerAuth: []

    put:
      summary: follow di un utente
      description: l'operazione aggiunge il followedUserId dall'array di seguiti dell'utente
      tags: ["following"]
      operationId: followUser
      responses:
        "204":
          description: Successo, utente seguito.
        "404":
          description: Errore, utente non trovato!
      security:
        - bearerAuth: []

  #
  /user/{idUser}/banned/: #con o senza / finale

    parameters: 
    - name: idUser
      in: path
      required: true
      description: id dell'utente della pagina visitata
      schema:
        type: integer
        description: es /user/260513/banned/


    get:
      summary: Utenti bloccati dall'utente
      description: l'operazione ritorna in un array la tutti gli utenti bloccati dall'utente
      tags: ["banned"]
      operationId: getMyBanList
      responses:
        "200":
          description: Successo, ricevuto la lista degli utenti bloccati
          content:
            application/json:
              schema:
                type: array
                minItems: 0
                maxItems: 999
                items:
                  $ref: "#/components/schemas/user"
      security:
        - bearerAuth: []

  #
  /user/{idUser}/banned/{bannedUserId}:
    parameters: 
    - name: idUser
      in: path
      required: true
      description: id dell'utente della pagina visitata
      schema:
        type: integer
        description: es /user/260513/banned/xxx


    - name: bannedUserId
      in: path
      required: true
      description: id dell'utente bannato
      schema:
        type: integer
        description: es /user/260513/banned/150519

    
    put:
      summary: Ban di un utente
      description: l'operazione inserisce il bannedUserId dall'array dei bannati dell'utente
      tags: ["banned"]
      operationId: banUser
      responses:
        "204":
          description: "Successo, utente aggiunto alla ban list"
        "404":
          description: Errore, utente non trovato!
      security:
        - bearerAuth: []

    delete:
      summary: unBan di un utente
      description: l'operazione elimina il bannedUserId dall'array dei bannati dell'utente
      tags: ["banned"]
      operationId: unbanUser
      responses:
        "204": 
          description: "Successo, utente rimosso dalla ban list"
        "404":
          description: Errore, utente non trovato!
      security:
        - bearerAuth: []



  #
  /user/{idUser}/images: #con o senza / finale
    parameters: 
    - name: idUser
      in: path
      required: true
      description: id dell'utente della pagina visitata
      schema:
        type: integer
        description: es /user/ads34f/images


    post:
      summary: Upload di un immagine
      description: l'operazione carica l'immagine inserita dall'utente
      tags: ["images"]
      operationId: uploadPhoto
      requestBody: 
        content: 
          application/json: 
            schema:
              $ref: "#/components/schemas/image"
      responses:
        "204":
          description: Successo, immagine caricata
      security:
        - bearerAuth: []

  /user/{idUser}/images/{imageId}:
    parameters: 
      - name: idUser
        in: path
        required: true
        description: id dell'utente della pagina visitata
        schema:
          type: integer
          description: es /user/260519/images/xxx


      - name: imageId
        in: path
        required: true
        description: id dell'immagine
        schema:
          type: string
          description: es /user/260519/images/afs23f3qf
          pattern: '^.*?$'
          minLength: 4
          maxLength: 25
          example: dfsvweggssd
    
    delete:
      summary: Rimozione di un immagine
      description: elimina l'immagine imageId dell'utente
      tags: ["images"]
      operationId: deletePhoto
      responses:
        "204":
          description: Successo, immagine eliminata
        "404":
          description: Errore, immagine non trovata!
      security:
        - bearerAuth: []

    get:
      summary: Accesso ad un'immagine
      description: ritorna l'immagine imageId dell'utente
      tags: ["images"]
      operationId: getTheImage
      responses:
        "200":
          description: Successo, accesso all'immagine 
          content: 
            application/json: 
              schema:
                $ref: "#/components/schemas/image"
        "404":
          description: Errore, immagine non trovata!
      security:
        - bearerAuth: []

  #
  /user/{idUser}/images/{imageId}/like/: #con o senza / finale
    parameters:
    - name: idUser
      in: path
      required: true
      description: id dell'utente della pagina visitata
      schema:
        type: integer
        description: es /user/260519/images/xxx/like/

    - name: imageId
      in: path
      required: true
      description: id dell'immagine
      schema:
        type: string
        description: es /user/260519/images/23f32ff3/like/
        pattern: '^.*?$'
        minLength: 4
        maxLength: 25
        example: dfsvweggssd

    get:
      summary: Lista degli utenti che hanno messo like alla foto
      description: ritorna la lista degli utenti che hanno messo like alla foto imageId
      tags: ["like"]
      operationId: getMyLike
      responses:
        "200":
          description: Successo, ricevuto la lista degli utenti che hanno messo like!
          content:
            application/json:
              schema:
                type: array
                minItems: 0
                maxItems: 999
                items:
                  $ref: "#/components/schemas/user"
      security:
        - bearerAuth: []

  /user/{idUser}/images/{imageId}/like/{likeUserId}:
    parameters:
      - name: idUser
        in: path
        required: true
        description: id dell'utente della pagina visitata
        schema:
          type: integer
          description: es /user/260519/images/xxx/like/xxx


      - name: imageId
        in: path
        required: true
        description: id dell'immagine
        schema:
          type: string
          description: es /user/260519/images/g324gsd/like/xxx
          pattern: '^.*?$'
          minLength: 4
          maxLength: 25
          example: dfsvweggssd

      - name: likeUserId
        in: path
        required: true
        description: id dell'utente che mette like
        schema:
          type: integer
          description: es /user/260519/images/g324gsd/like/234234


    put:
      summary: inserimento dell'utente nella lista dei like della foto
      description: inserisce nell'array dei like della foto (imageId) likeUserId
      tags: ["like"]      
      operationId: likePhoto
      responses:
        "204":
          description: "Successo, utente aggiunto alla lista dei like della foto"
        "404":
          description: Errore, utente non trovato!
      security:
        - bearerAuth: []

    delete:
      summary: rimozione dell'utente nella lista dei like della foto
      description: elimina nell'array dei like della foto (imageId) likeUserId
      tags: ["like"]      
      operationId: unlikePhoto
      responses:
        "204":
          description: "Successo, utente eliminato dalla lista dei like della foto"
        "404":
          description: Errore, utente non trovato!
      security:
        - bearerAuth: []


  #
  /user/{idUser}/images/{imageId}/comments/: #con o senza / finale
    parameters:
      - name: idUser
        in: path
        required: true
        description: id dell'utente della pagina visitata
        schema:
          type: integer
          description: es /user/2334423/images/xxx/comments/

      - name: imageId
        in: path
        required: true
        description: id dell'immagine
        schema:
          type: string
          description: es /user/2334423/images/asdasd/comments/
          pattern: '^.*?$'
          minLength: 4
          maxLength: 25
          example: dfsvweggssd

    get:
      summary: Lista degli utenti e dei commenti lasciati sotto la foto
      description: ritorna in un array la lista degli utenti e dei commenti lasciati sotto la foto
      tags: ["comment"]
      operationId: getMyComments
      responses:
        "200":
          description: Successo, ricevuto la lista degli utenti che hanno messo like!
          content:
            application/json:
              schema:
                type: array
                minItems: 0
                maxItems: 999
                items:
                  type: object
                  properties:
                    idComment:
                      description: id del commento
                      type: string
                      pattern: '^.*?$'
                      minLength: 4
                      maxLength: 25
                      example: agfhd029f2f
                    text:
                      description: testo del commento
                      type: string
                      pattern: '^.*?$'
                      minLength: 1
                      maxLength: 80
                      example: bella foto!
                    commenter:
                      description: utente che ha commentato
                      type: integer
      security:
        - bearerAuth: []
    
    post:  # il server deve creare l'id del commento
      summary: inserimento del commento 
      description: invia al server il commento e l'utente che ha commentato la foto, post perche' il server crea l'id del commento
      tags: ["comment"]
      operationId: commentPhoto
      requestBody:
        content:
          application/json:
            schema: 
              type: object
              properties:
                Commenter:
                  description: utente che ha commentato
                  type: integer
                text:
                  description: testo del commento
                  type: string
                  pattern: '^.*?$'
                  minLength: 1
                  maxLength: 80
                  example: bella foto!
      responses:
        "204":
          description: "Successo, commento inserito dalla lista dei commenti della foto"
      security:
        - bearerAuth: []


  /user/{idUser}/images/{imageId}/comments/{commentId}:
    parameters:
      - name: idUser
        in: path
        required: true
        description: id dell'utente della pagina visitata
        schema:
          type: integer
          description: es /user/2334423/images/xxx/comments/xxx

      - name: imageId
        in: path
        required: true
        description: id dell'immagine
        schema:
          type: string
          description: es /user/2334423/images/f2323f/comments/xxx
          pattern: '^.*?$'
          minLength: 4
          maxLength: 25
          example: dfsvweggssd

      - name: commentId
        in: path
        required: true
        description: id del commento
        schema:
          type: string
          description: es /user/2334423/images/f2323f/comments/fewfff3
          pattern: '^.*?$'
          minLength: 4
          maxLength: 25
          example: agfhd029f2f

    delete:
      summary: rimozione dell'utente nella lista dei commenti della foto
      description: elimina nell'array dei commenti della foto (imageId) commentId
      tags: ["comment"]
      operationId: uncommentPhoto
      responses:
        "204":
          description: "Successo, commento eliminato dalla foto"
      security:
        - bearerAuth: []

  #
  /session:
    post:
      tags: ["login"]
      summary: Logs in the user
      description: accede al servizio
      operationId: doLogin
      requestBody:
        description: User details
        content:
          application/json:
            schema:
              type: object
              properties:
                name:   
                  description: nome dell'utente per il login
                  type: string
                  example: mariaa
                  pattern: 'ˆ.*?$'
                  minLength: 3
                  maxLength: 16
        required: true
      responses:
        '201':
          description: User log-in action successful
          content:   
            application/json:
              schema: 
                type: integer


                    
                  
        
      